"""Plans tiered manifest + browse-by-Set + drift check (Set plans-adopter, Order 03).

``aw plans index [--check]`` regenerates ``.agents/plans/INDEX.json`` (every plan, all fields) and a
browse-by-``Set:`` human view (``INDEX.md``: each Set lists its members in ``Order``, Sets ordered by
most-recent activity, bounded to the 40 most-recent Sets, the rest available in the JSON). ``aw plans
find`` queries the manifest. ``--check`` fails on the four drift classes (missing/invalid ``Id``,
name-vs-metadata mismatch on a clustered name, stale generated view, dangling plan citation).

Consumes the shared core (Order 01: id6, Drift shape, dangling detector) and the required plan
``Id`` (Order 02). The scan is RECURSIVE so plans that Order 05 moves into
``<disposition>/YYYYMM/`` shards remain visible; disposition is the TOP-LEVEL directory even
when a plan sits in a shard subdir. Complements (does not replace) the disposition-grouped
``STATUS.md`` from ``plans.py``.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

from agent_workflows import artifact_core as _core

DEFAULT_INDEX_LIMIT = 40  # OQ5: browse-by-Set view bounded to the N most-recent Sets.
# (The former module-level `PLANS_DIR = ".agents/plans"` was dead - resolution is via `_dirs()` /
# `resolve_record_path` - and was removed in Order 05, S5-DC01.)
INDEX_JSON = "INDEX.json"
INDEX_MD = "INDEX.md"
_MD_HEADER = "<!-- generated by `aw index plans`; do not edit by hand -->"

_META_RE = {
    "Date": re.compile(r"(?m)^- Date:\s*(.+?)\s*$"),
    "Kind": re.compile(r"(?m)^- Kind:\s*(.+?)\s*$"),
    "Status": re.compile(r"(?m)^- Status:\s*(.+?)\s*$"),
    "Id": re.compile(r"(?m)^- Id:\s*([0-9a-z]{6})\s*$"),
    "Set": re.compile(r"(?m)^- Set:\s*(.+?)\s*$"),
    "Order": re.compile(r"(?m)^- Order:\s*(\d+)\s*$"),
}

_EXCLUDE_NAMES = {"INDEX.json", "INDEX.md", "STATUS.md", "README.md"}


class PlanEntry(NamedTuple):
    """One indexed plan (derived from its disposition dir + metadata)."""

    plan_id: Optional[str]
    path: str  # posix, relative to the plans dir
    disposition: (
        str  # top-level dir (pending/executed/superseded/not-executed/reusable)
    )
    date: str
    set_id: Optional[str]
    order: Optional[int]
    status: Optional[str]
    kind: Optional[str]


def _meta(text: str, key: str) -> Optional[str]:
    m = _META_RE[key].search(text)
    return m.group(1) if m else None


def set_terse_id(raw: Optional[str]) -> Optional[str]:
    """Extract the canonical terse set-id from a `Set:` value of the form ``<terse> (<descriptive>)``.

    The leading whitespace-delimited token before any ``(`` is the set-id; the parenthetical is a
    human-readable display name (plans-adopter Order 06). A bare terse id (no parenthetical) also
    parses. Returns None for None.
    """

    if raw is None:
        return None
    return raw.split("(", 1)[0].strip() or None


def scan_plans(plans_dir: Path) -> Tuple[List[PlanEntry], List[_core.Drift]]:
    """Recursively scan every plan under ``plans_dir``; return (entries, drift).

    Disposition is the first path component under ``plans_dir`` (so a plan inside a
    ``<disposition>/YYYYMM/`` shard keeps its top-level disposition). Drift here covers the
    metadata classes (missing/invalid Id); name-vs-metadata and stale-view/dangling are added by
    ``check_drift``.
    """

    entries: List[PlanEntry] = []
    drift: List[_core.Drift] = []
    if not plans_dir.is_dir():
        return entries, drift
    for p in sorted(plans_dir.rglob("*.md")):
        if p.name in _EXCLUDE_NAMES:
            continue
        rel = p.relative_to(plans_dir).as_posix()
        disposition = rel.split("/", 1)[0]
        text = p.read_text(encoding="utf-8")
        plan_id = _meta(text, "Id")
        order_raw = _meta(text, "Order")
        entries.append(
            PlanEntry(
                plan_id=plan_id,
                path=rel,
                disposition=disposition,
                date=str(_meta(text, "Date") or ""),
                set_id=set_terse_id(_meta(text, "Set")),
                order=int(order_raw) if order_raw else None,
                status=_meta(text, "Status"),
                kind=_meta(text, "Kind"),
            )
        )
        # Drift class (a): missing/invalid Id. Terminal grandfathered plans are still expected to
        # carry an Id after migration; report a missing/invalid one regardless of disposition.
        if plan_id is None:
            drift.append(_core.Drift(rel, "id-missing", "no `- Id:` metadata line"))
        elif not _core.is_valid_id6(plan_id):
            drift.append(
                _core.Drift(
                    rel, "id-invalid", f"Id '{plan_id}' is not a 6-char base36 token"
                )
            )
    return entries, drift


def build_index_json(entries: List[PlanEntry]) -> str:
    """Render the complete plans manifest as deterministic JSON (sorted by path)."""

    payload = [e._asdict() for e in sorted(entries, key=lambda e: e.path)]
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _set_last_touched(entries: List[PlanEntry]) -> Dict[str, str]:
    lt: Dict[str, str] = {}
    for e in entries:
        key = e.set_id or f"(singleton) {e.path}"
        if key not in lt or e.date > lt[key]:
            lt[key] = e.date
    return lt


def build_index_md(entries: List[PlanEntry], limit: int = DEFAULT_INDEX_LIMIT) -> str:
    """Render the browse-by-Set view: group by Set, members in Order, Sets by recent activity,
    bounded to the N most-recent Sets; Set-less plans in a singleton band."""

    last_touched = _set_last_touched(entries)
    # Group by Set (Set-less -> the singleton band, keyed by None).
    by_set: Dict[Optional[str], List[PlanEntry]] = {}
    for e in entries:
        by_set.setdefault(e.set_id, []).append(e)

    real_sets = [s for s in by_set if s is not None]

    def _inv_date(d: str) -> str:
        return "".join(str(9 - int(c)) if c.isdigit() else c for c in d) if d else ""

    # Sets ordered by most-recent activity (desc), tie-broken by set-id asc.
    ordered_sets = sorted(
        real_sets, key=lambda s: (_inv_date(last_touched.get(s, "")), s)
    )
    shown = ordered_sets[:limit]

    lines = [_MD_HEADER, "", "# Plans by topic (Set)", ""]
    lines.append(
        f"Showing the {len(shown)} most-recent of {len(real_sets)} Sets; the full manifest is INDEX.json."
    )
    lines.append("")
    for s in shown:
        members = sorted(
            by_set[s], key=lambda e: (e.order if e.order is not None else 0, e.path)
        )
        lines.append(f"## {s}")
        lines.append("")
        for e in members:
            oid = f"{e.order:02d}" if e.order is not None else "--"
            pid = e.plan_id or "??????"
            lines.append(f"- `{pid}` [{e.disposition}] {oid} {e.path}")
        lines.append("")
    singletons = by_set.get(None, [])
    if singletons:
        lines.append("## (singletons: no Set)")
        lines.append("")
        for e in sorted(singletons, key=lambda e: e.path):
            pid = e.plan_id or "??????"
            lines.append(f"- `{pid}` [{e.disposition}] {e.path}")
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------------------
# find
# --------------------------------------------------------------------------------------


def query(
    entries: List[PlanEntry],
    *,
    plan_id: Optional[str] = None,
    set_id: Optional[str] = None,
    status: Optional[str] = None,
    disposition: Optional[str] = None,
) -> List[PlanEntry]:
    out = list(entries)
    if plan_id:
        out = [e for e in out if e.plan_id == plan_id]
    if set_id:
        out = [e for e in out if e.set_id == set_id]
    if status:
        out = [e for e in out if e.status == status]
    if disposition:
        out = [e for e in out if e.disposition == disposition]
    return sorted(out, key=lambda e: (e.set_id or "", e.order or 0, e.path))


# --------------------------------------------------------------------------------------
# citation matcher + current-id resolver for the dangling detector (plan area)
# --------------------------------------------------------------------------------------

# A plan CITATION: the clustered/full plan filename OR a bare stem that resolves to a PLAN via the
# manifest. To avoid the specs-namespace collision, the dangling detector resolves ids from the
# plan manifest only; a bare stem is matched by the caller-supplied resolver, not blindly.
_PLAN_ID_CITE_RE = re.compile(r"\bPLAN-([0-9a-z]{6})\b")


def _plan_cite_matcher(line: str) -> List[str]:
    """Extract plan-id citations: the explicit ``PLAN-<id6>`` handle (bare stems/filenames resolve
    via the manifest path, not by id, so they are handled by the rename tool in Order 04)."""

    return _PLAN_ID_CITE_RE.findall(line)


# --------------------------------------------------------------------------------------
# check
# --------------------------------------------------------------------------------------


def check_drift(
    repo_root: Path, plans_dir: Path, limit: int = DEFAULT_INDEX_LIMIT
) -> List[_core.Drift]:
    entries, drift = scan_plans(plans_dir)
    # Drift class (b): name-vs-metadata mismatch on a CLUSTERED name only. Old-style
    # YYYYMMDD-HHMM-NN-slug.md names can coincidentally fit the clustering regex (HHMM as a set-id,
    # a slug's first letters as an id6), so distinguish by the second segment: the clustering grammar
    # never has a 4-digit HHMM there (a set-id is kebab, not exactly 4 digits). A name is treated as
    # clustered only when the regex matches AND the second segment is not a bare 4-digit HHMM.
    for e in entries:
        base = Path(e.path).name
        m = re.match(
            r"\A\d{8}-(?P<set>[a-z0-9-]+?)-(?P<nn>\d{2})-(?P<id6>[0-9a-z]{6})-[a-z0-9-]+\.md\Z",
            base,
        )
        if not m or re.fullmatch(r"\d{4}", m.group("set")):
            continue  # not clustered (or an old-style HHMM name)
        if e.plan_id and m.group("id6") != e.plan_id:
            drift.append(
                _core.Drift(
                    e.path,
                    "name-metadata-mismatch",
                    f"name id {m.group('id6')} != metadata Id {e.plan_id}",
                )
            )
        if e.set_id and m.group("set") != e.set_id:
            drift.append(
                _core.Drift(
                    e.path,
                    "name-metadata-mismatch",
                    f"name set {m.group('set')} != metadata Set {e.set_id}",
                )
            )
    # Drift class (c): stale generated view (byte-compare in memory vs disk).
    want_json = build_index_json(entries)
    want_md = build_index_md(entries, limit=limit)
    jp = plans_dir / INDEX_JSON
    mp = plans_dir / INDEX_MD
    if not jp.is_file() or jp.read_text(encoding="utf-8") != want_json:
        drift.append(
            _core.Drift(
                INDEX_JSON, "stale-index", "INDEX.json is missing or out of date"
            )
        )
    if not mp.is_file() or mp.read_text(encoding="utf-8") != want_md:
        drift.append(
            _core.Drift(INDEX_MD, "stale-index", "INDEX.md is missing or out of date")
        )
    # Drift class (d): dangling plan citation via the shared-core detector.
    current_ids = {e.plan_id for e in entries if e.plan_id}
    for d in _core.find_dangling_citations(
        repo_root,
        current_ids=current_ids,
        cite_matcher=_plan_cite_matcher,
        exclude_root=plans_dir,
    ):
        drift.append(
            _core.Drift(f"{d.file}:{d.line}", "dangling-citation", f"PLAN-{d.id6}")
        )
    return drift


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def _dirs(args: argparse.Namespace) -> Tuple[Path, Path]:
    from agent_workflows.project_context import resolve_verb_repo_root

    repo_root = resolve_verb_repo_root(getattr(args, "dir", None))
    from agent_workflows.record_producers import resolve_record_path

    try:
        plans_dir = resolve_record_path("plans", target_repo=str(repo_root))
    except Exception:
        plans_dir = repo_root / ".aw" / "records" / "plans"
    if not plans_dir.is_dir() and (repo_root / ".agents" / "plans").is_dir():
        plans_dir = repo_root / ".agents" / "plans"
    elif not plans_dir.is_dir() and (repo_root / ".aw" / "records" / "plans").is_dir():
        plans_dir = repo_root / ".aw" / "records" / "plans"
    return repo_root, plans_dir


def run_index(args: argparse.Namespace) -> int:
    repo_root, plans_dir = _dirs(args)
    limit = getattr(args, "limit", None) or DEFAULT_INDEX_LIMIT
    if getattr(args, "check", False):
        drift = check_drift(repo_root, plans_dir, limit=limit)
        if getattr(args, "agent", False):
            print(_core.render_agent_drift(drift), end="")
            return _core.drift_exit_code(drift)
        if not drift:
            print("plans index --check: clean")
            return 0
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
        return 1
    entries, drift = scan_plans(plans_dir)
    plans_dir.mkdir(parents=True, exist_ok=True)
    (plans_dir / INDEX_JSON).write_text(build_index_json(entries), encoding="utf-8")
    (plans_dir / INDEX_MD).write_text(
        build_index_md(entries, limit=limit), encoding="utf-8"
    )
    # Regeneration always writes the CURRENT state (a snapshot); metadata drift (e.g. a plan still
    # lacking an Id) is reported but does NOT block the write. Use `--check` as the gate.
    if drift and not getattr(args, "quiet", False):
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
    if not getattr(args, "quiet", False):
        print(f"wrote {INDEX_JSON} + {INDEX_MD} ({len(entries)} plans)")
    return 0


def run_find(args: argparse.Namespace) -> int:
    repo_root, plans_dir = _dirs(args)
    entries, _drift = scan_plans(plans_dir)
    results = query(
        entries,
        plan_id=getattr(args, "id", None),
        set_id=getattr(args, "set", None),
        status=getattr(args, "status", None),
        disposition=getattr(args, "disposition", None),
    )
    if not results:
        from agent_workflows.term import Term
        from agent_workflows.result_types import NextAction

        filters_dict = {}
        for k in ("id", "set", "status", "disposition"):
            v = getattr(args, k, None)
            if v:
                filters_dict[k] = v
        Term().empty_result(
            summary="no matching plans",
            filters=filters_dict if filters_dict else None,
            next_action=NextAction(
                command="aw find plans", description="find across all plans"
            )
            if filters_dict
            else NextAction(
                command="aw ipd scaffold", description="scaffold a new plan"
            ),
        )
        return 0
    for e in results:
        print(f"{e.plan_id or '??????'}\t{e.disposition}\t{e.set_id or '-'}\t{e.path}")
    return 0
