"""Scan plan/prompt lifecycle files and read their readiness ``Status:`` (DECISIONS D52/Dnn).

This is the single source of truth for the plan readiness vocabulary and the legacy mapping. It is
shared by the ``aw plans`` board (``cli.py``) and the repo drift-guard test
(``tests/test_plan_status.py``), so the two can never diverge.

Directories carry DISPOSITION (pending/executed/superseded/not-executed/reusable; ``done`` is an
accepted alias for ``executed``). The front-matter ``- Status:`` line carries READINESS. See D52 and
``.agents/workflows/assess/templates/ipd.md``.

Everything here is stdlib-only (zero runtime deps, D46). It READS front-matter only; it never
renames, moves, or writes plan files (``render_status_index`` returns text; the caller writes it).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional

# Readiness vocabulary (D52). Lowercase-kebab; front-matter is the single source of truth.
PRE_TERMINAL = ("draft", "to-review", "reviewed", "approved")
TERMINAL = ("executed", "superseded", "not-executed")
STANDING = ("reusable",)
RECOGNIZED = frozenset(PRE_TERMINAL + TERMINAL + STANDING)

# Disposition directories under .agents/plans (and the `done` alias for executed).
DISPOSITION_DIRS = (
    "pending",
    "executed",
    "superseded",
    "not-executed",
    "reusable",
    "done",
)
DIR_TERMINAL = {
    "executed": "executed",
    "superseded": "superseded",
    "not-executed": "not-executed",
}

# Legacy free-text status -> canonical readiness (D52 backward-compat). Case-normalized first.
LEGACY_MAP = {
    "pending": "to-review",
    "done": "executed",  # `done` is the accepted alias for `executed`
}

# Group/sort order for the board: lifecycle order, then legacy/unknown last.
_READINESS_ORDER = {
    name: i for i, name in enumerate(PRE_TERMINAL + TERMINAL + STANDING)
}
LEGACY_GROUP = "legacy/unknown"

_STATUS_RE = re.compile(r"^- Status:\s*(?P<val>\S+)", re.MULTILINE)


class PlanRecord(NamedTuple):
    path: Path
    area: str  # "plans" or "prompts"
    disposition: str  # the directory name (pending/executed/... or "" if top-level)
    status: Optional[str]  # canonical readiness, LEGACY_GROUP, or None (no status)


def normalize_status(raw: Optional[str]) -> Optional[str]:
    """Case-normalize and legacy-map a raw Status token to the canonical vocabulary.

    Returns a recognized readiness value, ``LEGACY_GROUP`` for an unrecognized token, or ``None``
    when there is no status at all.
    """

    if raw is None:
        return None
    val = raw.strip().rstrip(".").lower()
    if not val:
        return None
    val = LEGACY_MAP.get(val, val)
    return val if val in RECOGNIZED else LEGACY_GROUP


def read_status(md: Path) -> Optional[str]:
    """Return the canonical readiness status parsed from a file's front-matter, or None."""

    try:
        text = md.read_text(encoding="utf-8")
    except OSError:
        return None
    m = _STATUS_RE.search(text)
    return normalize_status(m.group("val")) if m else None


def scan(root: Path, include_prompts: bool = True) -> List[PlanRecord]:
    """Scan ``<root>/.agents/plans`` (and ``.agents/prompts``) for plan/prompt records.

    Reads front-matter only; renames/moves nothing. ``README.md`` files are skipped. Returns an
    empty list when the areas do not exist.
    """

    records: List[PlanRecord] = []
    agents = root / ".agents"
    areas = ["plans"] + (["prompts"] if include_prompts else [])
    for area in areas:
        base = agents / area
        if not base.is_dir():
            continue
        for disp in DISPOSITION_DIRS:
            d = base / disp
            if not d.is_dir():
                continue
            for f in sorted(d.glob("*.md")):
                if f.name == "README.md":
                    continue
                records.append(PlanRecord(f, area, disp, read_status(f)))
    return records


def group(records: List[PlanRecord]) -> "Dict[str, Dict[str, List[PlanRecord]]]":
    """Group records by disposition dir, then by readiness status (lifecycle-ordered)."""

    by_disp: Dict[str, Dict[str, List[PlanRecord]]] = {}
    for rec in records:
        status = rec.status if rec.status is not None else "(no status)"
        by_disp.setdefault(rec.disposition, {}).setdefault(status, []).append(rec)
    return by_disp


def _status_sort_key(status: str):
    return (_READINESS_ORDER.get(status, len(_READINESS_ORDER) + 1), status)


def render_status_index(root: Path, records: List[PlanRecord]) -> str:
    """Return a deterministic plain-Markdown STATUS.md body (grouped list, OQ1).

    Deterministic ordering so re-running ``--write-index`` produces no spurious diff.
    """

    lines = [
        "# Plan status index",
        "",
        "Generated by `aw plans --write-index` (do not edit by hand). Front-matter `Status:` is the "
        "source of truth; the directory is the disposition. See DECISIONS D52.",
        "",
    ]
    by_disp = group(records)
    total = len(records)
    lines.append(f"Total: {total} plan/prompt file(s).")
    lines.append("")
    for disp in DISPOSITION_DIRS:
        statuses = by_disp.get(disp)
        if not statuses:
            continue
        count = sum(len(v) for v in statuses.values())
        lines.append(f"## {disp}/ ({count})")
        lines.append("")
        for status in sorted(statuses, key=_status_sort_key):
            recs = statuses[status]
            lines.append(f"- **{status}** ({len(recs)})")
            for rec in sorted(recs, key=lambda r: r.path.name):
                lines.append(f"  - `{rec.path.relative_to(root).as_posix()}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
