"""Prompts tiered manifest + browse-by-Set + drift check (Plan dx0u4s).

``aw prompts index [--check]`` regenerates ``.aw/records/prompts/INDEX.json`` (every prompt, all fields)
and a browse-by-``Set:`` human view (``INDEX.md``: each Set lists its members in ``Order``, Sets ordered
by most-recent activity, bounded to the 40 most-recent Sets, the rest available in the JSON).
``--check`` fails on drift (missing/stale generated views, name-metadata mismatches).

Consumes the shared core (`artifact_core`) and `artifact_naming`.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

from agent_workflows import artifact_core as _core
from agent_workflows import artifact_naming as _naming

DEFAULT_INDEX_LIMIT = 40
INDEX_JSON = "INDEX.json"
INDEX_MD = "INDEX.md"
_MD_HEADER = "<!-- generated by `aw index prompts`; do not edit by hand -->"

_EXCLUDE_NAMES = {"INDEX.json", "INDEX.md", "README.md"}

# The legacy staged staging name: YYYYMMDD-HHMM-NN-<slug>.prompt.md
_STAGED_NAME_RE = re.compile(
    r"\A(?P<date>\d{8})-(?P<hhmm>\d{4})-(?P<nn>\d{2})-(?P<slug>[a-z0-9-]+)"
    r"(?:\.(?P<facet>[a-z0-9.-]+))?\.md\Z"
)


class PromptEntry(NamedTuple):
    """One indexed prompt (derived from its disposition dir, filename, and metadata comment)."""

    id6: Optional[str]
    path: str  # posix, relative to prompts_dir
    disposition: str  # pending/executed/superseded/not-executed/reusable
    date: str
    set_id: Optional[str]
    order: Optional[int]
    status: Optional[str]
    kind: Optional[str]
    slug: Optional[str] = None


def _parse_metadata_comment(text: str) -> Dict[str, str]:
    first = text.split("\n", 1)[0] if text else ""
    if not (
        first.startswith("<!--") and "aw-prompt:" in first and first.endswith("-->")
    ):
        return {}
    inner = first[4:-3].strip()
    if inner.startswith("aw-prompt:"):
        inner = inner[len("aw-prompt:") :].strip()
    if " . This HTML comment is" in inner:
        inner = inner.split(" . This HTML comment is", 1)[0].strip()
    elif " . " in inner:
        inner = inner.split(" . ", 1)[0].strip()
    meta = {}
    for part in inner.split("|"):
        part = part.strip()
        if ":" in part:
            k, v = part.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta


def scan_prompts(prompts_dir: Path) -> Tuple[List[PromptEntry], List[_core.Drift]]:
    """Scan every prompt under ``prompts_dir``; return (entries, drift)."""
    entries: List[PromptEntry] = []
    drift: List[_core.Drift] = []
    if not prompts_dir.is_dir():
        return entries, drift
    ignored_dirs = _core.get_ignored_dirs(prompts_dir)
    for p in sorted(prompts_dir.rglob("*.md")):
        if p.name in _EXCLUDE_NAMES or _core.is_ignored_path(
            p, prompts_dir, ignored_dirs
        ):
            continue
        rel = p.relative_to(prompts_dir).as_posix()
        disposition = rel.split("/", 1)[0]
        text = p.read_text(encoding="utf-8")
        meta = _parse_metadata_comment(text)

        m = _naming.parse_clustered(p.name)
        if m:
            fn_date = m.group("date")
            fn_set = m.group("set")
            try:
                fn_order = int(m.group("nn")) if m.group("nn") else None
            except (ValueError, TypeError):
                fn_order = None
            fn_id6 = m.group("id6")
            fn_slug = m.group("slug")
        else:
            m_leg = _STAGED_NAME_RE.match(p.name)
            if m_leg:
                fn_date = m_leg.group("date")
                fn_set = None
                try:
                    fn_order = int(m_leg.group("nn")) if m_leg.group("nn") else None
                except (ValueError, TypeError):
                    fn_order = None
                fn_id6 = None
                fn_slug = m_leg.group("slug")
            else:
                fn_date = ""
                fn_set = None
                fn_order = None
                fn_id6 = None
                fn_slug = None

        id6 = meta.get("Id") or fn_id6
        set_id = meta.get("Set") or fn_set
        order_raw = meta.get("Order")
        order = int(order_raw) if order_raw and order_raw.isdigit() else fn_order
        date = meta.get("Created") or meta.get("Date") or fn_date or ""
        kind = meta.get("Kind")
        status = meta.get("Status") or disposition
        slug = meta.get("Slug") or fn_slug

        entries.append(
            PromptEntry(
                id6=id6,
                path=rel,
                disposition=disposition,
                date=date,
                set_id=set_id,
                order=order,
                status=status,
                kind=kind,
                slug=slug,
            )
        )
    return entries, drift


def build_index_json(entries: List[PromptEntry]) -> str:
    """Render the complete prompts manifest as deterministic JSON (sorted by path)."""
    payload = [e._asdict() for e in sorted(entries, key=lambda e: e.path)]
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _set_last_touched(entries: List[PromptEntry]) -> Dict[str, str]:
    lt: Dict[str, str] = {}
    for e in entries:
        key = e.set_id or f"(singleton) {e.path}"
        if key not in lt or e.date > lt[key]:
            lt[key] = e.date
    return lt


def build_index_md(entries: List[PromptEntry], limit: int = DEFAULT_INDEX_LIMIT) -> str:
    """Render the browse-by-Set view: group by Set, members in Order, Sets by recent activity,
    bounded to the N most-recent Sets; Set-less prompts in a singleton band."""
    last_touched = _set_last_touched(entries)
    by_set: Dict[Optional[str], List[PromptEntry]] = {}
    for e in entries:
        by_set.setdefault(e.set_id, []).append(e)

    real_sets = [s for s in by_set if s is not None]

    def _inv_date(d: str) -> str:
        return "".join(str(9 - int(c)) if c.isdigit() else c for c in d) if d else ""

    ordered_sets = sorted(
        real_sets, key=lambda s: (_inv_date(last_touched.get(s, "")), s)
    )
    shown = ordered_sets[:limit]

    lines = [_MD_HEADER, "", "# Prompts by topic (Set)", ""]
    lines.append(
        f"Showing the {len(shown)} most-recent of {len(real_sets)} Sets; the full manifest is INDEX.json."
    )
    lines.append("")
    for s in shown:
        members = sorted(
            by_set[s], key=lambda e: (e.order if e.order is not None else 0, e.path)
        )
        lines.append(f"## {s}")
        lines.append("")
        for e in members:
            oid = f"{e.order:02d}" if e.order is not None else "--"
            pid = e.id6 or "??????"
            lines.append(f"- `{pid}` [{e.disposition}] {oid} {e.path}")
        lines.append("")
    singletons = by_set.get(None, [])
    if singletons:
        lines.append("## (singletons: no Set)")
        lines.append("")
        for e in sorted(singletons, key=lambda e: e.path):
            pid = e.id6 or "??????"
            lines.append(f"- `{pid}` [{e.disposition}] {e.path}")
        lines.append("")
    return "\n".join(lines)


def check_drift(
    repo_root: Path, prompts_dir: Path, limit: int = DEFAULT_INDEX_LIMIT
) -> List[_core.Drift]:
    entries, drift = scan_prompts(prompts_dir)
    from agent_workflows import check_engine as _ce

    # Drift: name-vs-metadata mismatch on a clustered name
    for e in entries:
        base = Path(e.path).name
        m = _naming.parse_clustered(base)
        if not m or re.fullmatch(r"\d{4}", m.group("set")):
            continue
        try:
            full_path = prompts_dir / e.path
            text = full_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        meta = _parse_metadata_comment(text)
        comment_id = meta.get("Id")
        if comment_id and m.group("id6") != comment_id:
            drift.append(
                _core.Drift(
                    e.path,
                    "name-metadata-mismatch",
                    f"name id {m.group('id6')} != metadata Id {comment_id}",
                )
            )
        comment_set = meta.get("Set")
        if comment_set and m.group("set") != comment_set:
            drift.append(
                _core.Drift(
                    e.path,
                    "name-metadata-mismatch",
                    f"name set {m.group('set')} != metadata Set {comment_set}",
                )
            )

    want_json = build_index_json(entries)
    want_md = build_index_md(entries, limit=limit)
    jp = prompts_dir / INDEX_JSON
    mp = prompts_dir / INDEX_MD

    for path_const, exists, matches, label in (
        (
            INDEX_JSON,
            jp.is_file(),
            jp.is_file() and jp.read_text(encoding="utf-8") == want_json,
            "INDEX.json",
        ),
        (
            INDEX_MD,
            mp.is_file(),
            mp.is_file() and mp.read_text(encoding="utf-8") == want_md,
            "INDEX.md",
        ),
    ):
        if not exists:
            drift.append(
                _ce.enrich_drift(
                    _core.Drift(
                        path_const,
                        "check.stale-index-missing",
                        f"{label} has not been generated; run 'aw index prompts'",
                    ),
                    recovery="aw index prompts",
                )
            )
        elif not matches:
            drift.append(
                _ce.enrich_drift(
                    _core.Drift(
                        path_const,
                        "check.stale-index-stale",
                        f"{label} is out of date; run 'aw index prompts'",
                    ),
                    recovery="aw index prompts",
                )
            )

    return drift


def _dirs(args: argparse.Namespace) -> Tuple[Path, Path]:
    from agent_workflows.project_context import resolve_verb_repo_root
    from agent_workflows import prompts as _prompts

    repo_root = resolve_verb_repo_root(getattr(args, "dir", None))
    prompts_dir = _prompts.prompts_root(repo_root)
    return repo_root, prompts_dir


def run_index(args: argparse.Namespace) -> int:
    repo_root, prompts_dir = _dirs(args)
    limit = getattr(args, "limit", None) or DEFAULT_INDEX_LIMIT
    if getattr(args, "check", False):
        drift = check_drift(repo_root, prompts_dir, limit=limit)
        if getattr(args, "agent", False):
            print(_core.render_agent_drift(drift), end="")
            return _core.drift_exit_code(drift)
        if not drift:
            print("prompts index --check: clean")
            return 0
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
        return _core.drift_exit_code(drift)
    entries, drift = scan_prompts(prompts_dir)
    json_path = prompts_dir / INDEX_JSON
    md_path = prompts_dir / INDEX_MD
    new_json = build_index_json(entries)
    new_md = build_index_md(entries, limit=limit)

    json_changed = (not json_path.exists()) or (
        json_path.read_text(encoding="utf-8") != new_json
    )
    md_changed = (not md_path.exists()) or (
        md_path.read_text(encoding="utf-8") != new_md
    )

    if json_changed:
        json_path.write_text(new_json, encoding="utf-8")
    if md_changed:
        md_path.write_text(new_md, encoding="utf-8")

    if drift and not getattr(args, "quiet", False):
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
    if not getattr(args, "quiet", False):
        print(f"wrote {INDEX_JSON} ({len(entries)} prompts)")
        print(f"wrote {INDEX_MD}")
    return 0
