"""Research tiered index generator + query + drift check (Set research-org, Order 03).

``aw research index [--check]`` regenerates ``INDEX.json`` (every doc) and ``INDEX.md`` (the
most-recent-N hot glance: intake band + most-recent-N by set last-touched, reference INCLUDED,
archive EXCLUDED) purely from frontmatter. ``aw research find`` answers queries over the JSON
cheaply. ``--check`` fails on drift (the spec 5.2 four classes: missing/invalid frontmatter,
name-vs-frontmatter mismatch, stale generated view via in-memory byte-compare, AND a dangling
citation via Order 04's imported detector primitive).

The generator is a PURE, deterministic function of frontmatter (no model/network; the only writes
are the two generated files, and only under the non-check path). INDEX.md ordering uses a total
deterministic sort (set last-touched desc, then set-id, then id6) so equal dates never reorder.
Consumes Order 01 (contract) and Order 04 (dangling detector); runs after both.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

from agent_workflows import artifact_core as _core
from agent_workflows import research_contract as R
from agent_workflows import research_refs as RF

# OQ2: the default hot-window size, overridable via --limit. Kept here as the single constant.
DEFAULT_INDEX_LIMIT = 40

INDEX_JSON = "INDEX.json"
INDEX_MD = "INDEX.md"
_MD_HEADER = "<!-- generated by `aw research index`; do not edit by hand -->"


class DocEntry(NamedTuple):
    """One indexed research doc (derived purely from its filename + frontmatter)."""

    id6: str
    path: str  # posix, relative to the research root
    set_id: str
    order: str
    date: str  # set date from the name
    created: str
    topic: List[str]
    model: str
    kind: str
    status: str
    outcome: str
    summary: str


# The generic drift record is the shared core's (plans-adopter Order 01); re-export it.
Drift = _core.Drift


def _scan_docs(
    research_root: Path,
) -> Tuple[List[DocEntry], List[Drift]]:
    """Scan every research doc; return (entries, drift) where drift covers frontmatter/name classes."""

    entries: List[DocEntry] = []
    drift: List[Drift] = []
    if not research_root.is_dir():
        return entries, drift
    for p in sorted(research_root.rglob("*.md")):
        if p.name in (INDEX_MD,) or p.name == "README.md":
            continue
        parsed, name_err = R.parse_name(p.name)
        if parsed is None:
            # Non-conformant filename: not an indexable research doc; skip quietly (migration
            # handles back-fill). Only report a name-vs-frontmatter mismatch for files that DO
            # carry research frontmatter.
            text = p.read_text(encoding="utf-8")
            if R.parse_frontmatter(text) is not None:
                drift.append(
                    Drift(
                        p.name,
                        "name-invalid",
                        name_err.message if name_err else "bad name",
                    )
                )
            continue
        text = p.read_text(encoding="utf-8")
        fm = R.parse_frontmatter(text)
        rel = p.relative_to(research_root).as_posix()
        if fm is None:
            drift.append(
                Drift(rel, "frontmatter-missing", "no valid frontmatter block")
            )
            continue
        errs = R.validate_frontmatter(fm)
        if errs:
            for e in errs:
                drift.append(
                    Drift(rel, "frontmatter-invalid", f"{e.field}: {e.message}")
                )
            continue
        # name-vs-frontmatter consistency
        if fm.get("id") != parsed.id6:
            drift.append(
                Drift(
                    rel,
                    "name-frontmatter-mismatch",
                    f"id {fm.get('id')} != name {parsed.id6}",
                )
            )
        if fm.get("set") != parsed.set_id:
            drift.append(
                Drift(
                    rel,
                    "name-frontmatter-mismatch",
                    f"set {fm.get('set')} != name {parsed.set_id}",
                )
            )
        topic_val = fm.get("topic")
        topic_list = [str(t) for t in topic_val] if isinstance(topic_val, list) else []
        entries.append(
            DocEntry(
                id6=parsed.id6,
                path=rel,
                set_id=parsed.set_id,
                order=parsed.order,
                date=parsed.date,
                created=str(fm.get("created", "")),
                topic=topic_list,
                model=str(fm.get("model", "") or ""),
                kind=parsed.kind,
                status=str(fm.get("status", "")),
                outcome=str(fm.get("outcome", "")),
                summary=str(fm.get("summary", "")),
            )
        )
    return entries, drift


def _set_last_touched(entries: List[DocEntry]) -> Dict[str, str]:
    """Map set-id -> its last-touched date (max member `created`, fall back to set date)."""

    lt: Dict[str, str] = {}
    for e in entries:
        key = e.set_id
        stamp = e.created or e.date
        if key not in lt or stamp > lt[key]:
            lt[key] = stamp
    return lt


def build_index_json(entries: List[DocEntry]) -> str:
    """Render the complete manifest as deterministic JSON (every doc, sorted by id6)."""

    payload = [e._asdict() for e in sorted(entries, key=lambda e: e.id6)]
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build_index_md(entries: List[DocEntry], limit: int = DEFAULT_INDEX_LIMIT) -> str:
    """Render the bounded hot glance: intake band + most-recent-N, reference IN, archive OUT.

    Deterministic total order: set last-touched desc, then set-id asc, then id6 asc.
    """

    last_touched = _set_last_touched(entries)

    # Archive is excluded from the hot glance; intake/active/reference are eligible.
    glance = [e for e in entries if e.status != "archive"]

    # Total deterministic order: set last-touched DESC, then set-id ASC, then id6 ASC. We invert
    # only the date component (a lexical complement) so the tie-breakers stay ascending.
    def _inv_date(d: str) -> str:
        # Complement each digit so a lexical ascending sort yields descending dates.
        return "".join(str(9 - int(c)) if c.isdigit() else c for c in d)

    glance_sorted = sorted(
        glance,
        key=lambda e: (_inv_date(last_touched.get(e.set_id, e.date)), e.set_id, e.id6),
    )
    top = glance_sorted[:limit]

    intake = [e for e in entries if e.status == "intake"]

    lines = [_MD_HEADER, "", "# Research index", ""]
    lines.append(
        f"Showing the most-recent {min(limit, len(glance_sorted))} of {len(glance_sorted)} hot docs (archive excluded)."
    )
    lines.append("")
    if intake:
        lines.append("## Needs addressing (intake)")
        lines.append("")
        for e in sorted(intake, key=lambda e: (e.set_id, e.order)):
            lines.append(f"- `{e.id6}` {e.path} - {e.summary}")
        lines.append("")
    lines.append("## Most recent")
    lines.append("")
    for e in top:
        lines.append(f"- `{e.id6}` [{e.status}] {e.path} - {e.summary}")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------------------
# find
# --------------------------------------------------------------------------------------


def query(
    entries: List[DocEntry],
    *,
    id6: Optional[str] = None,
    set_id: Optional[str] = None,
    topic: Optional[str] = None,
    status: Optional[str] = None,
) -> List[DocEntry]:
    """Filter entries by any combination of id/set/topic/status (deterministic order)."""

    out = list(entries)
    if id6:
        out = [e for e in out if e.id6 == id6]
    if set_id:
        out = [e for e in out if e.set_id == set_id]
    if topic:
        out = [e for e in out if topic in e.topic]
    if status:
        out = [e for e in out if e.status == status]
    return sorted(out, key=lambda e: (e.set_id, e.order, e.id6))


# --------------------------------------------------------------------------------------
# check (the four drift classes)
# --------------------------------------------------------------------------------------


def check_drift(
    repo_root: Path, research_root: Path, limit: int = DEFAULT_INDEX_LIMIT
) -> List[Drift]:
    """Return every drift finding across the spec-5.2 four classes."""

    entries, drift = _scan_docs(research_root)
    # Stale generated view: regenerate in memory and byte-compare to disk.
    want_json = build_index_json(entries)
    want_md = build_index_md(entries, limit=limit)
    json_path = research_root / INDEX_JSON
    md_path = research_root / INDEX_MD
    if not json_path.is_file() or json_path.read_text(encoding="utf-8") != want_json:
        drift.append(
            Drift(INDEX_JSON, "stale-index", "INDEX.json is missing or out of date")
        )
    if not md_path.is_file() or md_path.read_text(encoding="utf-8") != want_md:
        drift.append(
            Drift(INDEX_MD, "stale-index", "INDEX.md is missing or out of date")
        )
    # Dangling citations via Order 04's imported detector primitive.
    for d in RF.find_dangling_citations(repo_root, research_root):
        drift.append(Drift(f"{d.file}:{d.line}", "dangling-citation", f"id6 {d.id6}"))
    return drift


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def _roots(args: argparse.Namespace) -> Tuple[Path, Path]:
    repo_root = Path(getattr(args, "dir", None) or ".").resolve()
    from agent_workflows.record_producers import resolve_record_path

    try:
        res_root = resolve_record_path("research", target_repo=str(repo_root))
    except Exception:
        res_root = repo_root / ".aw" / "records" / "research"
    if not res_root.is_dir() and (repo_root / ".agents" / "docs" / "research").is_dir():
        res_root = repo_root / ".agents" / "docs" / "research"
    return repo_root, res_root


def run_index(args: argparse.Namespace) -> int:
    repo_root, research_root = _roots(args)
    limit = getattr(args, "limit", None) or DEFAULT_INDEX_LIMIT
    if getattr(args, "check", False):
        drift = check_drift(repo_root, research_root, limit=limit)
        if getattr(args, "agent", False):
            for d in drift:
                print(f"{d.location}\t{d.rule}\t{d.detail}")
            return 1 if drift else 0
        if not drift:
            print("index --check: clean")
            return 0
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
        return 1
    # Regenerate.
    entries, drift = _scan_docs(research_root)
    if drift:
        # Refuse to write over invalid input; report and exit nonzero.
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
        return 1
    research_root.mkdir(parents=True, exist_ok=True)
    (research_root / INDEX_JSON).write_text(build_index_json(entries), encoding="utf-8")
    (research_root / INDEX_MD).write_text(
        build_index_md(entries, limit=limit), encoding="utf-8"
    )
    print(f"wrote {INDEX_JSON} + {INDEX_MD} ({len(entries)} docs)")
    return 0


def run_find(args: argparse.Namespace) -> int:
    repo_root, research_root = _roots(args)
    entries, _drift = _scan_docs(research_root)
    results = query(
        entries,
        id6=getattr(args, "id", None),
        set_id=getattr(args, "set", None),
        topic=getattr(args, "topic", None),
        status=getattr(args, "status", None),
    )
    if not results:
        print("no matching research docs")
        return 0
    for e in results:
        print(f"{e.id6}\t{e.status}\t{e.path}\t{e.summary}")
    return 0
