"""Research tiered index generator + query + drift check (Set research-org, Order 03).

``aw research index [--check]`` regenerates ``INDEX.json`` (every doc) and ``INDEX.md`` (the
most-recent-N hot glance: intake band + most-recent-N by set last-touched, reference INCLUDED,
archive EXCLUDED) purely from frontmatter. ``aw research find`` answers queries over the JSON
cheaply. ``--check`` fails on drift (the spec 5.2 four classes: missing/invalid frontmatter,
name-vs-frontmatter mismatch, stale generated view via in-memory byte-compare, AND a dangling
citation via Order 04's imported detector primitive).

The generator is a PURE, deterministic function of frontmatter (no model/network; the only writes
are the two generated files, and only under the non-check path). INDEX.md ordering uses a total
deterministic sort (set last-touched desc, then set-id, then id6) so equal dates never reorder.
Consumes Order 01 (contract) and Order 04 (dangling detector); runs after both.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, NamedTuple, Optional, Tuple

from agent_workflows import artifact_core as _core
from agent_workflows import research_contract as R
from agent_workflows import research_refs as RF

# OQ2: the default hot-window size, overridable via --limit. Kept here as the single constant.
DEFAULT_INDEX_LIMIT = 40

INDEX_JSON = "INDEX.json"
INDEX_MD = "INDEX.md"
_MD_HEADER = "<!-- generated by `aw research index`; do not edit by hand -->"


class DocEntry(NamedTuple):
    """One indexed research doc (derived purely from its filename + frontmatter)."""

    id6: str
    path: str  # posix, relative to the research root
    set_id: str
    order: str
    date: str  # set date from the name
    created: str
    topic: List[str]
    model: str
    kind: str
    status: str
    outcome: str
    summary: str


# The generic drift record is the shared core's (plans-adopter Order 01); re-export it.
Drift = _core.Drift


def _scan_docs(
    research_root: Path,
) -> Tuple[List[DocEntry], List[Drift]]:
    """Scan every research doc; return (entries, drift) where drift covers frontmatter/name classes."""

    entries: List[DocEntry] = []
    drift: List[Drift] = []
    if not research_root.is_dir():
        return entries, drift
    for p in sorted(research_root.rglob("*.md")):
        if p.name in (INDEX_MD,) or p.name == "README.md":
            continue
        parsed, name_err = R.parse_name(p.name)
        if parsed is None:
            # Non-conformant filename: not an indexable research doc; skip quietly (migration
            # handles back-fill). Only report a name-vs-frontmatter mismatch for files that DO
            # carry research frontmatter.
            text = p.read_text(encoding="utf-8")
            if R.parse_frontmatter(text) is not None:
                drift.append(
                    Drift(
                        p.name,
                        "name-invalid",
                        name_err.message if name_err else "bad name",
                    )
                )
            continue
        text = p.read_text(encoding="utf-8")
        fm = R.parse_frontmatter(text)
        rel = p.relative_to(research_root).as_posix()
        if fm is None:
            drift.append(
                Drift(rel, "frontmatter-missing", "no valid frontmatter block")
            )
            continue
        errs = R.validate_frontmatter(fm)
        if errs:
            for e in errs:
                drift.append(
                    Drift(rel, "frontmatter-invalid", f"{e.field}: {e.message}")
                )
            continue
        # name-vs-frontmatter consistency
        if fm.get("id") != parsed.id6:
            drift.append(
                Drift(
                    rel,
                    "name-frontmatter-mismatch",
                    f"id {fm.get('id')} != name {parsed.id6}",
                )
            )
        if fm.get("set") != parsed.set_id:
            drift.append(
                Drift(
                    rel,
                    "name-frontmatter-mismatch",
                    f"set {fm.get('set')} != name {parsed.set_id}",
                )
            )
        topic_val = fm.get("topic")
        topic_list = [str(t) for t in topic_val] if isinstance(topic_val, list) else []
        entries.append(
            DocEntry(
                id6=parsed.id6,
                path=rel,
                set_id=parsed.set_id,
                order=parsed.order,
                date=parsed.date,
                created=str(fm.get("created", "")),
                topic=topic_list,
                model=str(fm.get("model", "") or ""),
                kind=parsed.kind,
                status=str(fm.get("status", "")),
                outcome=str(fm.get("outcome", "")),
                summary=str(fm.get("summary", "")),
            )
        )
    return entries, drift


def _set_last_touched(entries: List[DocEntry]) -> Dict[str, str]:
    """Map set-id -> its last-touched date (max member `created`, fall back to set date)."""

    lt: Dict[str, str] = {}
    for e in entries:
        key = e.set_id
        stamp = e.created or e.date
        if key not in lt or stamp > lt[key]:
            lt[key] = stamp
    return lt


def build_index_json(entries: List[DocEntry]) -> str:
    """Render the complete manifest as deterministic JSON (every doc, sorted by id6)."""

    payload = [e._asdict() for e in sorted(entries, key=lambda e: e.id6)]
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build_index_md(entries: List[DocEntry], limit: int = DEFAULT_INDEX_LIMIT) -> str:
    """Render the bounded hot glance: intake band + most-recent-N, reference IN, archive OUT.

    Deterministic total order: set last-touched desc, then set-id asc, then id6 asc.
    """

    last_touched = _set_last_touched(entries)

    # Archive is excluded from the hot glance; intake/active/reference are eligible.
    glance = [e for e in entries if e.status != "archive"]

    # Total deterministic order: set last-touched DESC, then set-id ASC, then id6 ASC. We invert
    # only the date component (a lexical complement) so the tie-breakers stay ascending.
    def _inv_date(d: str) -> str:
        # Complement each digit so a lexical ascending sort yields descending dates.
        return "".join(str(9 - int(c)) if c.isdigit() else c for c in d)

    glance_sorted = sorted(
        glance,
        key=lambda e: (_inv_date(last_touched.get(e.set_id, e.date)), e.set_id, e.id6),
    )
    top = glance_sorted[:limit]

    intake = [e for e in entries if e.status == "intake"]

    lines = [_MD_HEADER, "", "# Research index", ""]
    lines.append(
        f"Showing the most-recent {min(limit, len(glance_sorted))} of {len(glance_sorted)} hot docs (archive excluded)."
    )
    lines.append("")
    if intake:
        lines.append("## Needs addressing (intake)")
        lines.append("")
        for e in sorted(intake, key=lambda e: (e.set_id, e.order)):
            lines.append(f"- `{e.id6}` {e.path} - {e.summary}")
        lines.append("")
    lines.append("## Most recent")
    lines.append("")
    for e in top:
        lines.append(f"- `{e.id6}` [{e.status}] {e.path} - {e.summary}")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------------------
# find
# --------------------------------------------------------------------------------------


def query(
    entries: List[DocEntry],
    *,
    id6: Optional[str] = None,
    set_id: Optional[str] = None,
    topic: Optional[str] = None,
    status: Optional[str] = None,
) -> List[DocEntry]:
    """Filter entries by any combination of id/set/topic/status (deterministic order)."""

    out = list(entries)
    if id6:
        out = [e for e in out if e.id6 == id6]
    if set_id:
        out = [e for e in out if e.set_id == set_id]
    if topic:
        out = [e for e in out if topic in e.topic]
    if status:
        out = [e for e in out if e.status == status]
    return sorted(out, key=lambda e: (e.set_id, e.order, e.id6))


# --------------------------------------------------------------------------------------
# unrun / RUN derivation (IPD m383qb E-01): a purely structural signal over the manifest
# --------------------------------------------------------------------------------------


def derive_unrun_prompts(entries: List[DocEntry]) -> List[DocEntry]:
    """Return the UNRUN research prompts, derived purely from set structure (no corpus read).

    A SET is UNRUN when its ``NN=00`` member is a ``research-prompt`` and the set has NO
    ``NN>=01`` sibling member; the set is RUN otherwise (a report/reconciliation sibling exists).
    Docs with no parseable set/order are treated as singletons (never unrun prompts unless they
    are themselves a bare ``NN=00`` prompt). Deterministic order (set-id, then id6).

    This is the single reusable derivation consumed by the drift check (E-02) and later children
    (``aw research pending`` / attention surfacing, child 03). It reads ONLY the indexed manifest
    entries (filename + frontmatter), never the document bodies.
    """

    by_set: Dict[str, List[DocEntry]] = {}
    for e in entries:
        by_set.setdefault(e.set_id, []).append(e)

    unrun: List[DocEntry] = []
    for _set_id, members in by_set.items():
        prompt = next(
            (m for m in members if m.order == "00" and m.kind == "research-prompt"),
            None,
        )
        if prompt is None:
            continue
        has_sibling = any(m.order > "00" for m in members)
        if not has_sibling:
            unrun.append(prompt)
    return sorted(unrun, key=lambda e: (e.set_id, e.id6))


def unrun_set_ids(entries: List[DocEntry]) -> set:
    """The set-ids that are structurally UNRUN (a bare NN=00 prompt with no NN>=01 sibling)."""

    return {e.set_id for e in derive_unrun_prompts(entries)}


def run_prompt_set_ids(entries: List[DocEntry]) -> set:
    """The set-ids that are RUN PROMPT sets: a set with a ``NN=00 research-prompt`` AND at least
    one ``NN>=01`` sibling. Sets with no prompt at all are NOT part of the prompt run/unrun
    taxonomy (so an ordinary lone intake doc's set is neither run nor unrun here)."""

    by_set: Dict[str, List[DocEntry]] = {}
    for e in entries:
        by_set.setdefault(e.set_id, []).append(e)
    out: set = set()
    for set_id, members in by_set.items():
        has_prompt = any(
            m.order == "00" and m.kind == "research-prompt" for m in members
        )
        has_sibling = any(m.order > "00" for m in members)
        if has_prompt and has_sibling:
            out.add(set_id)
    return out


# --------------------------------------------------------------------------------------
# cited-by-executed derivation (IPD m383qb E-02): which research id6s are cited by an
# EXECUTED artifact (plan under executed/, spec implemented, or backlog item done). This is
# the REVERSE of find_dangling_citations (which finds a doc's OWN unresolved citations): here
# we scan executed artifacts and collect citations that resolve to a research id6. Built on the
# shared primitives (iter_scan_files + R.iter_id6_citations); does NOT bend find_dangling_citations.
# --------------------------------------------------------------------------------------


def _under(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _plan_is_executed(path: Path, repo_root: Path) -> bool:
    """True when a plan file sits under an ``executed/`` disposition directory.

    A plan's disposition is the first path component under the plans root (kept even inside a
    ``executed/YYYYMM/`` shard). We look at the repo-relative parts so the repo's own directory
    names cannot false-trigger.
    """

    parts = path.relative_to(repo_root).parts if _under(path, repo_root) else path.parts
    if "plans" not in parts:
        return False
    idx = parts.index("plans")
    return idx + 1 < len(parts) and parts[idx + 1] == "executed"


def _spec_is_implemented(text: str) -> bool:
    from agent_workflows import attention_contract as _A

    lines = text.splitlines()
    end = len(lines)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            end = i
            break
    for i in range(end):
        m = _A.SPEC_STATUS_RE.match(lines[i])
        if m:
            return m.group("value") == "implemented"
    return False


def _backlog_is_done(path: Path, text: str) -> bool:
    # Directory disposition takes precedence (an item under done/ is done), then the bullet Status.
    if path.parent.name == "done":
        return True
    for line in text.split("\n"):
        if line.startswith("## "):
            break
        m = re.match(r"^- Status:[ \t]*(?P<value>\S+)[ \t]*$", line)
        if m:
            return m.group("value") == "done"
    return False


def cited_by_executed_ids(repo_root: Path, research_root: Path) -> set:
    """Return the research id6s that are cited by an EXECUTED artifact.

    An artifact is executed when: it is a plan file under an ``executed/`` disposition dir; OR a
    spec whose metadata ``Status:`` is ``implemented``; OR a backlog item that is ``done`` (its
    ``done/`` dir or a ``- Status: done`` bullet). A citation from a merely pending/draft artifact
    does NOT count. Reuses ``iter_scan_files`` + ``R.iter_id6_citations`` (the shared citation
    primitives); the research tree itself is excluded so a doc citing another research doc is not
    treated as an executed-artifact citation here.
    """

    cited: set = set()
    for f in _core.iter_scan_files(repo_root):
        # Skip the research tree itself (we want EXECUTED plan/spec/backlog citers).
        if _under(f, research_root):
            continue
        parts = f.parts
        is_plan = "plans" in parts and f.name.endswith(".md")
        is_spec = "specs" in parts and f.name.endswith(".md")
        is_backlog = "backlog" in parts and f.name.endswith(".md")
        if not (is_plan or is_spec or is_backlog):
            continue
        try:
            text = f.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        executed = False
        if is_plan:
            executed = _plan_is_executed(f, repo_root)
        elif is_spec:
            executed = _spec_is_implemented(text)
        elif is_backlog:
            executed = _backlog_is_done(f, text)
        if not executed:
            continue
        for cid in R.iter_id6_citations(text):
            cited.add(cid)
    return cited


# --------------------------------------------------------------------------------------
# check (the four drift classes + the stale-state-to-promote rule)
# --------------------------------------------------------------------------------------

STALE_STATE_RULE = "stale-state-to-promote"


def check_drift(
    repo_root: Path, research_root: Path, limit: int = DEFAULT_INDEX_LIMIT
) -> List[Drift]:
    """Return every drift finding across the spec-5.2 four classes."""

    entries, drift = _scan_docs(research_root)
    # Stale generated view: regenerate in memory and byte-compare to disk.
    want_json = build_index_json(entries)
    want_md = build_index_md(entries, limit=limit)
    json_path = research_root / INDEX_JSON
    md_path = research_root / INDEX_MD
    if not json_path.is_file() or json_path.read_text(encoding="utf-8") != want_json:
        drift.append(
            Drift(INDEX_JSON, "stale-index", "INDEX.json is missing or out of date")
        )
    if not md_path.is_file() or md_path.read_text(encoding="utf-8") != want_md:
        drift.append(
            Drift(INDEX_MD, "stale-index", "INDEX.md is missing or out of date")
        )
    # Dangling citations via Order 04's imported detector primitive.
    for d in RF.find_dangling_citations(repo_root, research_root):
        drift.append(Drift(f"{d.file}:{d.line}", "dangling-citation", f"id6 {d.id6}"))
    # Stale-state-to-promote (IPD m383qb E-02): an intake/active doc whose SET is RUN
    # (structural, E-01) OR that is cited by an EXECUTED artifact is stale hot state and must be
    # promoted. Keeps state honest without trusting the hand-typed status.
    hot = [e for e in entries if e.status in R.HOT_STATUSES]
    if hot:
        run_sets = run_prompt_set_ids(entries)
        cited_exec = cited_by_executed_ids(repo_root, research_root)
        for e in hot:
            if e.set_id in run_sets:
                drift.append(
                    Drift(
                        e.path,
                        STALE_STATE_RULE,
                        f"{e.status} doc in RUN set '{e.set_id}'; promote it",
                    )
                )
            elif e.id6 in cited_exec:
                drift.append(
                    Drift(
                        e.path,
                        STALE_STATE_RULE,
                        f"{e.status} doc cited by an executed artifact; promote it",
                    )
                )
    return drift


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def _roots(args: argparse.Namespace) -> Tuple[Path, Path]:
    from agent_workflows.project_context import resolve_verb_repo_root

    repo_root = resolve_verb_repo_root(getattr(args, "dir", None))
    from agent_workflows.record_producers import resolve_record_path

    try:
        res_root = resolve_record_path("research", target_repo=str(repo_root))
    except Exception:
        res_root = repo_root / ".aw" / "records" / "research"
    if not res_root.is_dir() and (repo_root / ".agents" / "docs" / "research").is_dir():
        res_root = repo_root / ".agents" / "docs" / "research"
    elif (
        not res_root.is_dir() and (repo_root / ".aw" / "records" / "research").is_dir()
    ):
        res_root = repo_root / ".aw" / "records" / "research"
    return repo_root, res_root


def run_index(args: argparse.Namespace) -> int:
    repo_root, research_root = _roots(args)
    limit = getattr(args, "limit", None) or DEFAULT_INDEX_LIMIT
    if getattr(args, "check", False):
        drift = check_drift(repo_root, research_root, limit=limit)
        if getattr(args, "agent", False):
            for d in drift:
                print(f"{d.location}\t{d.rule}\t{d.detail}")
            return 1 if drift else 0
        if not drift:
            print("index --check: clean")
            return 0
        for d in drift:
            print(f"{d.location}: {d.rule}: {d.detail}")
        return 1
    # Regenerate.
    entries, drift = _scan_docs(research_root)
    if drift:
        # Refuse to write over invalid input; report and exit nonzero.
        if not getattr(args, "quiet", False):
            for d in drift:
                print(f"{d.location}: {d.rule}: {d.detail}")
        return 1
    json_path = research_root / INDEX_JSON
    md_path = research_root / INDEX_MD
    new_json = build_index_json(entries)
    new_md = build_index_md(entries, limit=limit)

    json_changed = (not json_path.exists()) or (
        json_path.read_text(encoding="utf-8") != new_json
    )
    md_changed = (not md_path.exists()) or (
        md_path.read_text(encoding="utf-8") != new_md
    )

    if json_changed:
        json_path.write_text(new_json, encoding="utf-8")
    if md_changed:
        md_path.write_text(new_md, encoding="utf-8")

    if not getattr(args, "quiet", False):
        from agent_workflows.term import Term

        term = Term(color=not getattr(args, "no_color", False))
        try:
            rel_dir = research_root.relative_to(repo_root).as_posix()
        except ValueError:
            rel_dir = research_root.as_posix()
        dir_prefix = f"{rel_dir}/" if rel_dir and not rel_dir.endswith("/") else rel_dir
        dir_styled = term.color256(dir_prefix, 33)

        if not json_changed and not md_changed:
            status_lbl = term.status_256("up to date", width=12)
            files_str = f"{dir_styled}{INDEX_JSON}, {INDEX_MD}"
            term.line(f"{status_lbl} {files_str} ({len(entries)} docs)")
        elif json_changed and md_changed:
            status_lbl = term.status_256("wrote", width=12)
            files_str = f"{dir_styled}{INDEX_JSON}, {INDEX_MD}"
            term.line(f"{status_lbl} {files_str} ({len(entries)} docs)")
        elif md_changed:
            status_lbl = term.status_256("updated", width=12)
            files_str = f"{dir_styled}{INDEX_MD}"
            term.line(
                f"{status_lbl} {files_str} ({INDEX_JSON} up to date; {len(entries)} docs)"
            )
        else:
            status_lbl = term.status_256("updated", width=12)
            files_str = f"{dir_styled}{INDEX_JSON}"
            term.line(
                f"{status_lbl} {files_str} ({INDEX_MD} up to date; {len(entries)} docs)"
            )
    return 0


def run_find(args: argparse.Namespace) -> int:
    repo_root, research_root = _roots(args)
    entries, _drift = _scan_docs(research_root)
    results = query(
        entries,
        id6=getattr(args, "id", None),
        set_id=getattr(args, "set", None),
        topic=getattr(args, "topic", None),
        status=getattr(args, "status", None),
    )
    if not results:
        from agent_workflows.term import Term
        from agent_workflows.result_types import NextAction

        filters_dict = {}
        for k in ("id", "set", "topic", "status"):
            v = getattr(args, k, None)
            if v:
                filters_dict[k] = v
        Term().empty_result(
            summary="no matching research docs",
            filters=filters_dict if filters_dict else None,
            next_action=NextAction(
                command="aw research find", description="find across all research docs"
            )
            if filters_dict
            else NextAction(
                command="aw research new", description="create a new research doc"
            ),
        )
        return 0
    for e in results:
        print(f"{e.id6}\t{e.status}\t{e.path}\t{e.summary}")
    return 0
